#pragma once
#include "Common.h"
// ----- RASTERIZER ----- START
#define UBO_VIEW_PROJECTION_BINDING 0
#define UBO_DIRECTIONS_BINDING 1
#define SAMPLER_BINDING 0

// ----- RASTERIZER ----- END


// Deferred Renderer Bindings

// Geometry Pass
#define G_PASS_BINDING_PER_FRAME_CONSTANTS 0
#define G_PASS_BINDING_SAMPLER 1
#define G_PASS_BINDING_TEXTURE_ARRAY 2
//...

// Shading Pass

#define S_PASS_BINDING_PER_FRAME_CONSTANTS 0
#define S_PASS_BINDING_SAMPLER 1
#define S_PASS_BINDING_TEXTURE_ARRAY 2

// BOTH --- Particles
#define PARTICLES_VERTEX_BUFFER_BINDING_ID 0

// --- COMPUTE PASS
#define C_PARTICLE_STORAGE_BUFFER_BINDING	0 
#define C_UNIFORM_BUFFER_BINDING			1
#define C_VECTOR_FIELD_BINDING				2
#define C_TLAS_BINDING						2 + NUM_VECTOR_FIELDS 
#define C_OBJECT_DESCRIPTION_BINDING		2 + NUM_VECTOR_FIELDS + 1